kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c01
      image: nginx
      command: ["/bin/bash", "-c", "while true; do echo Hello-Bhupinder; sleep 5 ; done"]
        - containerPort: 80

        