kind: ReplicationController               
apiVersion: v1
metadata:
  name: myreplica-testpod8
spec:
  replicas: 2            
  selector:        
    myname: shivani                            
  template:                
    metadata:
      name: testpod6
      labels:            
        myname: shivani
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Hello-Shivani; sleep 5 ; done"]


