apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 3
  selector:
    app: vertex-rc
  template:
    metadata:
      name: complexpod
      labels:
        app: vertex-rc
    spec:
      containers:
        - name: nginxcon
          image: nginx
          ports:
            - containerPort: 80


