apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicacon
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: complexpod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcon
          image: shivani999/myjavaapp14nov22
          ports:
            - containerPort: 8080


